MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_densenet_backbone"
    FREEZE_AT: 0   # last layer to freeze in last denseblock
  DENSENET:
    OUT_FEATURES: ["SoleStage"]
    # CONV_BODY: "densenet121"   # default
    # OUT_CHANNELS: 1024   # default
    PRETRAINED: True
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    # SIZES: [[32, 64, 128, 256, 512]]  # Corresponding FPN strides: 1/4, 1/8, 1/16, 1/32, 1/64
    SIZES: [[128, 256, 512]]   # Faster R-CNN paper used this on images with shorter side 600
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios
    OFFSET: 0.0   # recommended to use 0.5
  RPN:
    HEAD_NAME: "StandardRPNHead"
    IN_FEATURES: ["SoleStage"]
    IOU_THRESHOLDS: [0.3, 0.7]
    IOU_LABELS: [0, -1, 1]
    BATCH_SIZE_PER_IMAGE: 256   # 128:128
    POSITIVE_FRACTION: 0.5
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
    NMS_THRESH: 0.7
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["SoleStage"]
    NUM_CLASSES: 10
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
    BATCH_SIZE_PER_IMAGE: 512   # use 128 or 256?
    POSITIVE_FRACTION: 0.25   # 128:384
    SCORE_THRESH_TEST: 0.5   # default 0.05, Audubon said 0.5
    NMS_THRESH_TEST: 0.7   # 0.5 default
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    # FC_DIM: 1024
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7   # can use 14 if our images are 640 (spatial size of features 20x20)
    POOLER_SAMPLING_RATIO: 2   # 0 default
  PIXEL_MEAN: [103.530, 116.280, 123.675]   # change to our dataset
  PIXEL_STD: [1.0, 1.0, 1.0]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02   # 0.001 AudubonF1
  STEPS: (60000, 80000)   # (500,) AudubonF21
  MAX_ITER: 90000   # 1000 AudubonF21
INPUT:
  MIN_SIZE_TRAIN: [640] # must be list
  MIN_SIZE_TEST: 640   # must be int
  FORMAT: "BGR"

# cfg.MODEL.PROPOSAL_GENERATOR.NAME = "RPN"   # don't think it's needed