project: audubon_f21
program: wandb_train_net.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  data_dir:
    value: './data'
  img_ext:
    value: '.JPEG'
  output_dir:
    value: './output/wandb_sweep/'
  model_type:
    value: 'fasterrcnn'
  model_config_file:
    value: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  pretrained_coco_model_weights:
    value: [True, False]
  max_iter:
    value: 1000
  learning_rate:
    value: [1e-2,5e-3,1e-3,5e-4,1e-4,1e-5]
  weight_decay:
    value: [1e-4, 1e-5, 1e-6,1e-7,0]
  batch_size:
    value: [4,8,16,32,48,64,128]
