project: audubon_f21
program: wandb_train_net.py
description: tune hyperparams for faster-rcnn R-50 FPN 1x
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  data_dir:
    value: './data'
  img_ext:
    value: '.JPEG'
  output_dir:
    value: './output/wandb_sweep/'
  model_type:
    value: 'faster-rcnn'
  model_config_file:
    value: "COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"
  pretrained_weights_file:
    values: ["", "COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"]
  max_iter:
    value: 1000
  learning_rate:
    values: [1e-2,5e-3,1e-3,5e-4,1e-4,1e-5]
  solver_warmup_factor:
    values: [1,1e-1,1e-2,1e-3]
  solver_warmup_iters:
    values: [1,100,200]
  weight_decay:
    values: [1e-4, 1e-5, 1e-6,1e-7,0]
  batch_size:
    value: 12
