project: audubon_f21
program: wandb_train_net.py
description: tune hyperparams for retinanet R50 FPN 3x
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  data_dir:
    value: './data'
  img_ext:
    value: '.JPEG'
  output_dir:
    value: './output/wandb_sweep/'
  model_type:
    value: 'retinanet'
  model_config_file:
    value: "COCO-Detection/retinanet_R_50_FPN_3x.yaml"
  pretrained_coco_model_weights:
    values: [True, False]
  max_iter:
    value: 1000
  learning_rate:
    values: [1e-2,5e-3,1e-3,5e-4,1e-4,1e-5,1e-7]
  solver_warmup_factor:
    values: [1,1e-1,1e-2,1e-3]
  solver_warmup_iters:
    values: [1,100]
  scheduler_steps:
    values: [[], [500,]]
  weight_decay:
    values: [1e-4, 1e-5, 1e-6,1e-7,0]
  batch_size:
    values: [4,6,8,12]
  focal_loss_gamma:
    values: [0,0.2,0.5,1.0,2.0,5.0]
  focal_loss_alpha:
    values: [0.25,0.5,0.75,0.9,0.99]


